# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Yanli LI
title: Artifitial Intelligence, Federated Learning, AI security, Machine Learning and More.
email: frank970519@gmail.com
# email_title: Email (Email title override)
# phone: +61-406950519 (8:00 a.m.-5:00 p.m)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
googlescholar_username: pKm8fHwAAAAJ&hl

# Additional icon links
# additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hello, this is Yanli Li, and I am currently working as a postdoc researcher at Nantong University (2024 - ) as well as a visting shcloar at the University of Sydney (2024 - ). 
  
  &nbsp;
  
  Under the PhD period, my research endeavors have been concentrated on **"Enhancing Federated Learning Robustness and Fairness in Non-IID Scenarios."** My academic pursuits encompass Federated Learning and Adversarial Machine Learning. Now, I expand my research areas to **DIfferential Privacy** and **Medical Applications** under the FL landscape. Please find my publications at the right top <mark>G</mark> icon. 
content:
  - title: Education
    layout: text
    content: |
      <strong style="font-size: 1.3em;">2020-2023 | University of Sydney | PhD </strong><br>
      
      **School of Electrical and Computer Engineering**<br>
      
      After completing my master's degree, I joined the University of Sydney to pursue a Ph.D. under the guidance of Dr. Yuan and Dr. Chen. I developed a keen interest in federated learning, particularly in its adversarial aspects. Federated learning is proposed to address the issue of data islands and the challenge of protecting user privacy in the real world—where user data cannot leave the user's device, yet there is still a desire to contribute data to train large models. Within the federated learning framework, users are often assumed to be potentially dishonest and malicious. In this context, I proposed several robust aggregation rules to mitigate the vulnerability of federated learning to attacks, tailored to different scenario requirements. Additionally, I also focused on issues related to fairness among different participants in distributed scenarios, as well as general problems in computer vision and language processing. <br><br>
  
      <strong style="font-size: 1.3em;">2018-2020 | The University of Technology Sydney | Master in Software Development </strong><br>   
      
      **School of Information Technology**<br>
      
      In 2018, I arrived in the beautiful city of Sydney to commence my graduate studies. During this period, I significantly enhanced my coding abilities. I engaged with and learned the C# programming language, advanced my skills in SQL databases, and acquired knowledge in game development. I designed and implemented several 2D mini-games based on Unity, such as Tetris and Pac-Man, among others. Additionally, I systematically studied various aspects of software development including project management and quality control. It is with great pride that I celebrate being placed on the Dean list for achieving an average grade over 85 during this time.<br><br>

      <strong style="font-size: 1.3em;">2013-2017 | Dalian University of Foreign Languages | Bechelor in Computer Science and Technology</strong><br>

      **School of Software**<br>

      At Dalian University of Foreign Languages, I undertook four years of undergraduate studies where I gained a foundational knowledge of computer science. During this time, I learned programming languages such as C++, Objective-C, Java Script, Java, and PHP, as well as data structures and SQL database knowledge. Additionally, I studied Japanese as my first foreign language and English as my second, experiencing the charm of different languages. In 2017, I graduated from Dalian University of Foreign Languages as an outstanding graduate.<br><br>


      
  - title: Honor
    layout: text
    content: | # this will include new lines to allow paragraphs
      <div style="text-align: center;">
        <img src="images/honor.jpeg" alt="honour" style="max-width:50%; height:auto;">
      </div>

 
# Footer
footer_show_references: False
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
